# Generated by Django 3.2 on 2024-01-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Расскажите о себе', verbose_name='О себе'),
        ),
    ]
