# Generated by Django 3.2.16 on 2024-01-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_auto_20240113_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя категории'),
        ),
    ]
