# Generated by Django 3.2 on 2024-01-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_alter_categories_name'),
        ('reviews', '0016_alter_title_year'),
    ]

    operations = [
    ]
