# Generated by Django 3.2 on 2024-01-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_auto_20240117_2251'),
        ('reviews', '0018_auto_20240117_1040'),
    ]

    operations = [
    ]
