# Generated by Django 3.2 on 2024-01-18 18:37

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_merge_0017_auto_20240117_2251_0018_auto_20240117_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[reviews.validators.validate_year], verbose_name='Год'),
        ),
    ]
