# Generated by Django 3.2 on 2024-01-19 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Нельзя поставить оценку ниже 1'), django.core.validators.MaxValueValidator(10, message='Нельзя поставить оценку выше 10')], verbose_name='Оценка'),
        ),
    ]
